### ISSUE TITLE
Parity with yab ratelimit

### ISSUE THREAD

**Issue by achals** [uber-go/ratelimit#10]
I was trawling through the yab ratelimiting code, and noticed that the [interface exposed](https://github.com/yarpc/yab/blob/dev/ratelimit/time_period.go#L35) there is different (and IMO nicer) than the interface in this package.

Is this package intended to be kept updated? If so, would it be possible to update the implementation to bring it up the parity? I'd be more than happy to contribute a PR if it would help. It would be great to be able to use rate limiting logic independently of yab.

**Comment by kriskowal** [comment]
A change of this kind would require a major version bump. It could be done, since nothing we know of uses this package yet. Ideally we *would* use this package as a dependency in yab. I’d like to know what @prashantv thinks.

**Comment by kriskowal** [comment]
To clarify, the difference is that yab’s take accepts a cancel channel.

**Comment by prashantv** [comment]
Since we haven't cut any releases, I think it's fine to change the interface.

I think the ideal interface would take a `context.Context` for cancellation.

**Comment by achals** [comment]
So I have a branch locally that updates the interface to accept a `context.Context`; it seems to be mostly working but `ExampleRateLimit` has way more variance than earlier:

```
--- FAIL: ExampleRatelimit (0.09s)
got:
1 10.935692ms
2 9.814699ms
3 11.718343ms
4 9.582154ms
5 8.356239ms
6 12.062452ms
7 8.729969ms
8 8.911591ms
9 9.937449ms
want:
1 10ms
2 10ms
3 10ms
4 10ms
5 10ms
6 10ms
7 10ms
8 10ms
9 10ms
FAIL
```

Again, go newb, but is switching to using `select` to block on channels supposed to add that kind of over head? I can make a PR if it helps the discussion.

**Comment by achals** [comment]
Ignore my earlier comment, I was misusing the `Clock` interface, which I've actually removed in my PR.

**Comment by nathanhack** [comment]
Is there a status on when the PR for this might be merged?
