### ISSUE TITLE
Take always return without block if it enters the case branch

### ISSUE THREAD

**Issue by smallnest** [uber-go/ratelimit#119]
https://github.com/uber-go/ratelimit/blob/main/limiter_atomic_int64.go#L72
```go
		case t.maxSlack > 0 && now-timeOfNextPermissionIssue > int64(t.maxSlack):
			// a lot of nanoseconds passed since the last Take call
			// we will limit max accumulated time to maxSlack
			newTimeOfNextPermissionIssue = now - int64(t.maxSlack)
```
 you will find the case always (almost) returns true.

The below code is a test for reproduce:
```go
func TestLimiter(t *testing.T) {
	limiter := ratelimit.New(1, ratelimit.Per(time.Second), ratelimit.WithSlack(1))

	for i := 0; i < 25; i++ {
		if i == 1 {
			time.Sleep(2 * time.Second)
		}
		limiter.Take()

		fmt.Println(time.Now().Unix(), i) // burst

	}
}
```

ratelimit is v0.3.0

**Comment by storozhukBM** [comment]
@smallnest can you please try the version from #120 and confirm that it works for you

**Comment by smallnest** [comment]
yes. Fixed. thanks

**Comment by spencercjh** [comment]
The fixed PR isn't merged, please re-open the issue to noticed the maintainer and other users to pay attention to the problem.
