### ISSUE TITLE
NewUnlimited() could use less memory

### ISSUE THREAD

**Issue by JensRantil** [uber-go/ratelimit#130]
...by returning a statically initialised instance of `unlimited`. Currently, it [allocates a new `unlimited` on every call](https://github.com/uber-go/ratelimit/blob/61eed72d6bdef7c5f51be1c7ae7c824750f53efe/ratelimit.go#L130). The `unlimited` instance is stateless.

**Comment by rabbbit** [comment]
That is depending on how you look at it ,though :)

https://dave.cheney.net/2014/03/25/the-empty-struct

> Now that we’ve explored width it should be evident that the empty struct has a width of zero. It occupies zero bytes of storage.

> As the empty struct consumes zero bytes, it follows that it needs no padding. Thus a struct comprised of empty structs also consumes no storage.

So it would seem it does not really matter. And so, I would avoid global variables as part of a good hygiene.

**Comment by JensRantil** [comment]
👍
