### ISSUE TITLE
Incorrect import path for atomic

### ISSUE THREAD

**Issue by leikao** [uber-go/ratelimit#18]
The *most correct* import path for `atomic` package should be `go.uber.org/atomic`, there is a mistake in the testing file:
https://github.com/uber-go/ratelimit/blob/c15da02342779cb6dc027fc95ee2277787698f36/ratelimit_test.go#L13

**Comment by leikao** [comment]
ping @kriskowal @prashantv

**Comment by kriskowal** [comment]
Thank you @leikao. This project probably predated the canonical import. Thankfully we depended on this only for tests!

I’ve posted a tag for v0.1.0 with this fix addressed.
