### ISSUE TITLE
Revisit mock clock naps

### ISSUE THREAD

**Issue by kriskowal** [uber-go/ratelimit#2]
Rather than nap in arbitrary real time, the mock clock should exhaust all goroutines executed in the context of the test until they are blocked on time.

**Comment by leonklingele** [comment]
What about calling [`pkg/runtime.Gosched()`](https://golang.org/pkg/runtime/#Gosched) instead of actually sleeping in [`nap()`](https://github.com/uber-go/ratelimit/blob/c15da02342779cb6dc027fc95ee2277787698f36/internal/clock/clock.go#L133)? Should have the same result?

**Comment by rabbbit** [comment]
Resolved in #39.
