### ISSUE TITLE
latest code is not being downloaded in go.mod

### ISSUE THREAD

**Issue by daltemen** [uber-go/ratelimit#25]
Using go.mod the version got was v0.1.0
`github.com/uber-go/ratelimit v0.1.0`

is it possible to create a new tag release to get the latest changes?

**Comment by rabbbit** [comment]
Hi,

You should see more activity in this repo soon, but for now please just use `go get go.uber.com@ecb970a6a3b3b0a49f74254576f1e939a1950aa4`

We don't want to release a new version until we're sure it's correct.
