### ISSUE TITLE
use of internal package go.uber.org/ratelimit/internal/clock not allowed

### ISSUE THREAD

**Issue by daltemen** [uber-go/ratelimit#26]
Tested with go 1.13 and go.mod.

```
../../../../../go/pkg/mod/github.com/uber-go/ratelimit@v0.1.1-0.20191205185619-ecb970a6a3b3/mutexbased.go:4:2: use of internal package go.uber.org/ratelimit/internal/clock not allowed
```

**Comment by noah8713** [comment]
@daltemen I faced the same issue while switching to go mod for a project. Submitted PR https://github.com/uber-go/ratelimit/pull/28 . PTAL

**Comment by prashantv** [comment]
Please import the package as `go.uber.org/ratelimit` to avoid the issue.

**Comment by rabbbit** [comment]
This seems resolved.
