### ISSUE TITLE
Whether to consider increasing the implementation of the token-bucket algorithm？

### ISSUE THREAD

**Issue by yunqiang-sun** [uber-go/ratelimit#62]
The description of this Repo is just contains leaky-bucket algorithm now, Now the interface defined in ratelimit.go is complete, Whether to consider increasing the implementation of the token-bucket algorithm？If you have such considerations, I can submit PR to contribute code

**Comment by rabbbit** [comment]
Hi,

Thanks for reaching out!

Good idea asking about this first - let's hold on with PRs until we hash it out.

So, no, we were not planning to extend the repo to include other types of rate limiters. If we were to change it, lets discuss why you'd like that to happen:
- is there a benefit of having both implementations in a single library as opposed to somewhere else?
- do you have a use case that needs both types?
- does the code already exist, and would you just copy it from somewhere?

Generally, if the point is just a CS exercise I don't think we'd be interested in adding it here - the implementation might just as well live somewhere else.

**Comment by yunqiang-sun** [comment]
> Hi,
> 
> Thanks for reaching out!
> 
> Good idea asking about this first - let's hold on with PRs until we hash it out.
> 
> So, no, we were not planning to extend the repo to include other types of rate limiters. If we were to change it, lets discuss why you'd like that to happen:
> 
> * is there a benefit of having both implementations in a single library as opposed to somewhere else?
> * do you have a use case that needs both types?
> * does the code already exist, and would you just copy it from somewhere?
> 
> Generally, if the point is just a CS exercise I don't think we'd be interested in adding it here - the implementation might just as well live somewhere else.

OK
