### ISSUE TITLE
Supply clock interface for testing?

### ISSUE THREAD

**Issue by MichaelSnowden** [uber-go/ratelimit#72]
I have some code which uses the ratelimiter that I'd like to test. However, the core functionality of my code is really time-based. For example, I'd like to verify that messages were sent at 5x their original rate. Doing this with the current ratelimiter would be tricky because I'd be relying on time.Now() and time.Sleep(). That does 2 things

1. Makes tests run longer than they need to
2. Introduces a race condition

Is it possible for the ratelimiter to take in a Clock interface that could make testing like this easier? For example:

```go
type Clock interface {
	Now() time.Time
	Sleep(duration time.Duration)
}

type TestClock struct {
	t time.Time
}

func (c *TestClock) Now() time.Time {
	return c.t
}

func (c *TestClock) Sleep(duration time.Duration) {
	c.t = c.t.Add(duration)
}

type RealClock struct {}

func (c *RealClock) Now() time.Time {
	return time.Now()
}

func (c *RealClock) Sleep(duration time.Duration) {
	time.Sleep(duration)
}
```

This would allow me to do something ilke

```go
clock := FakeClock{t: time.Now()}
limiter := ratelimit.New(messagesPerSecond, &clock)
output := myCodeUnderTest(limiter)
// verify the output
```

I see something like this in the ratelimit_test: https://github.com/uber-go/ratelimit/blob/main/ratelimit_test.go

However, I don't think that this method is public.

**Comment by abhinav** [comment]
Hello! Yes, you should be able to use the [WithClock](https://pkg.go.dev/go.uber.org/ratelimit#WithClock) option for this. Our Clock interface is intentionally light so you can either implement it yourself, or use an existing mock clock implementation like that test (which uses github.com/andres-erbsen/clock).

So your code sample above can be:

```go
clock := FakeClock{t: time.Now{()}
limiter := ratelimit.New(messagesPerSecond, ratelimit.WithClock(clock))
output := myCodeUnderTest(limiter)
// verify the output
```

Hope this answers your question. Closing.

**Comment by MichaelSnowden** [comment]
Thank you!
