### ISSUE TITLE
Support for increasing/decreasing limits on the fly

### ISSUE THREAD

**Issue by bcap** [uber-go/ratelimit#76]
This allows to implement nice things!

An example:
Implement an adaptative rate limiting from outside de library, enabling algorithms like:
1. start with a small ratelimiting value
2. periodically increase it by a small amount
3. notice errors, drop the rate limit by X%
4. potentially change the value of X (increase or decrease, make the algo converge better to optimal ratelimit)
5. loop back to 2

A suggestion for implementation is to keep a count of how many times `Take` was called in the given window and, when we increase or decrease, recalculate the sleep time. In case the window is already exploded (eg 10 per second is decreased to 5 per second, but in this second we already did 8 requests), then the next `Take` will wait for the whole window to finish.

From the current implementation I see there is no time window management, just a basic calculation of how much time we need to sleep in average between calls. This would maybe involve that, something to consider the complexity

**Comment by bcap** [comment]
Right now the poor man's option to have this is something managed outside the lib like this:
1. have a single rate limiter for normal ops
2. when an increase/decrease is requested, create a second rate limiter with the new value
3. `Take` takes from both rate limiters (we are in swapping mode here)
4. When the window of the first (old) rate limiter is expired, remove it
5. We are back at having a single rate limiter
6. The swapping mode is done, allowing more calls to increase/decrease again. Any calls to increase/decrease that were done while we were in swapping mode either got rejected, waiting (blocked) or executed later (async)

**Comment by shmilyoo** [comment]
you can wrap it, and use a block channel to stop the rate limit 
```
func (rl *RateLimit) Take() time.Time {
	<-rl.blockSignal
	return rl.throttle.Take()
}
```

**Comment by bruno-nascimento** [comment]
Hi, I know I must be missing something here 😓 
Why can't we have something like this to achieve the same goal ?
```
type Limiter struct {
	limiter ratelimit.Limiter
	mutex   sync.RWMutex
}

func NewLimiter(cfg config) Limiter {
	return Limiter{limiter: ratelimit.New(cfg.LimiterOperations, ratelimit.Per(cfg.LimiterDuration))}
}

func (l *Limiter) Update(ops int, duration time.Duration) {
	l.mutex.Lock()
	defer l.mutex.Unlock()
	l.limiter = ratelimit.New(ops, ratelimit.Per(duration))
}

func (l *Limiter) Take() time.Time {
	l.mutex.RLock()
	defer l.mutex.RUnlock()
	return l.limiter.Take()
}
```
As far as I could see, we could update the limiter while calling `limiter.Take()` from different go routines without any issue
```
time.AfterFunc(time.Second*5, func() {
        limiter.Update(3, time.Second)
})

time.AfterFunc(time.Second*10, func() {
        limiter.Update(20, time.Second)
})

time.AfterFunc(time.Second*15, func() {
        limiter.Update(100, time.Second)
})
```

**Comment by rabbbit** [comment]
Sorry, we don't foresee adding this to the library - contrary to your example, replacing the limit on the fly has non-obvious behavior wrt already existing limits and slack. Additionally, the extra lock defeats the purpose of the lock-less implementation we have.

Since, however, as your example shows it is simple enough to wrap this in your own code. We would encourage you to do just that if that fits your requirements.
