### ISSUE TITLE
What's the major diff v.s. https://pkg.go.dev/golang.org/x/time/rate

### ISSUE THREAD

**Issue by rmgogogo** [uber-go/ratelimit#77]
What's the major diff v.s. https://pkg.go.dev/golang.org/x/time/rate?
Any document or advanced planned features?

**Comment by rabbbit** [comment]
See [here](https://www.reddit.com/r/golang/comments/59k2bi/ubergoratelimit_a_golang_blocking_leakybucket/d99ob9q/?utm_source=reddit&utm_medium=web2x&context=3) for some historical context.

tldr;
- limited API
- lower overhead

There are no new planned features.
