### ISSUE TITLE
What is the difference with the "standard" rate limiting?

### ISSUE THREAD

**Issue by novikk** [uber-go/ratelimit#9]
Not an issue itself, just curious to know what is the difference with this and the advantages/disadvantages of each: https://github.com/golang/go/wiki/RateLimiting

**Comment by felix0080** [comment]
want too

**Comment by rabbbit** [comment]
Hi,

In https://github.com/golang/go/wiki/RateLimiting you pass in the "work" upfront, from a single go-routine, and the limiter takes care of sending the work at a scheduled interval.

This module has a different interface - it allows you to call it from a number of go-routines, as the work is available. Technically, you could build https://github.com/golang/go/wiki/RateLimiting using this module.

As to difference between this module and https://godoc.org/golang.org/x/time/rate - it's mostly similar, but at the time of creation of this module x/time/rate was ~10 times slower. We're not sure if that's still the case, we'll be looking more into the performance over the next weeks.
